'use strict';
document.head.insertAdjacentHTML('beforeend', '<link rel="stylesheet" href="/events.css">');
document.head.insertAdjacentHTML('beforeend', '<link rel="stylesheet" href="/event-images.css">');
let csrf = ''; let events = []; let contracts = [];
const $ = selector => document.querySelector(selector);
const loginPanel = $('#login-panel'), dashboard = $('#dashboard'), editor = $('#event-form');
const imageFile = $('#image-file'), imagePreview = $('#image-preview'), imagePreviewWrap = $('#image-preview-wrap');
const ticketType = editor.elements.ticketType, eventbriteField = $('#eventbrite-field'), ticketUrlField = $('#ticket-url-field');
let localImageUrl = '';
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]);
async function api(url, options = {}) { options.headers = { 'content-type':'application/json', ...(csrf ? {'x-csrf-token':csrf} : {}), ...options.headers }; const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Une erreur est survenue.'); return data; }
function message(form, text, ok = false) { const node = form.querySelector('.form-message'); node.textContent = text; node.classList.toggle('success', ok); }
function showDashboard() { loginPanel.classList.add('hidden'); dashboard.classList.remove('hidden'); $('#logout').classList.remove('hidden'); loadEvents(); loadContracts(); }
async function loadEvents() { events = await api('/api/events'); $('#admin-list').innerHTML = events.length ? events.map(event => `<button class="admin-event" data-id="${escapeHtml(event.id)}" type="button"><span><b>${escapeHtml(event.title)}</b><small>${escapeHtml(new Intl.DateTimeFormat('fr-CA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(event.date)))}</small></span><i class="status ${event.published?'live':''}">${event.published?'Publié':'Brouillon'}</i></button>`).join('') : '<p>Aucun événement.</p>'; }
function showImage(url) { imagePreview.src = url; imagePreviewWrap.classList.toggle('hidden', !url); }
function clearLocalImageUrl() { if (localImageUrl) URL.revokeObjectURL(localImageUrl); localImageUrl = ''; }
function updateTicketFields() { const type=ticketType.value; eventbriteField.classList.toggle('hidden',type!=='eventbrite'); ticketUrlField.classList.toggle('hidden',type!=='external'); editor.elements.eventbriteId.required=type==='eventbrite'; editor.elements.ticketUrl.required=type==='external'; }
function imageAsBase64(file) { return new Promise((resolve,reject) => { const reader=new FileReader(); reader.onload=()=>resolve(String(reader.result).split(',')[1]||''); reader.onerror=()=>reject(new Error('Lecture de l’image impossible.')); reader.readAsDataURL(file); }); }
function edit(event = null) { clearLocalImageUrl(); editor.reset(); editor.classList.remove('hidden'); $('#editor-title').textContent = event ? 'Modifier l’événement' : 'Nouvel événement'; $('#delete-event').classList.toggle('hidden', !event); editor.elements.id.value = event?.id || ''; if (event) { for (const [key,value] of Object.entries(event)) if (editor.elements[key]) editor.elements[key].type === 'checkbox' ? editor.elements[key].checked = value : editor.elements[key].value = value; } else { editor.elements.location.value='99, rue Saint-Georges, Saint-Jérôme'; editor.elements.organizer.value='Salle Point G'; editor.elements.image.value='/assets/point-g-salle.jpg'; editor.elements.ticketType.value='eventbrite'; editor.elements.eventbriteId.value='1998914026663'; } updateTicketFields(); imageFile.required = editor.elements.image.value === '/assets/point-g-salle.jpg'; showImage(editor.elements.image.value); message(editor, imageFile.required ? 'Sélectionnez une image pour remplacer l’image par défaut.' : ''); editor.scrollIntoView({behavior:'smooth',block:'start'}); }
ticketType.addEventListener('change',updateTicketFields);
imageFile.addEventListener('change', () => {
  const file = imageFile.files[0]; if (!file) return;
  if (file.size > 8 * 1024 * 1024) { message(editor, 'L’image dépasse la limite de 8 Mo.'); imageFile.value = ''; return; }
  if (!['image/jpeg','image/png','image/webp'].includes(file.type)) { message(editor, 'Choisissez une image JPEG, PNG ou WebP.'); imageFile.value = ''; return; }
  clearLocalImageUrl(); localImageUrl = URL.createObjectURL(file); showImage(localImageUrl); message(editor, `${file.name} est prête. Cliquez sur « Enregistrer » pour la téléverser.`, true);
});
$('#login-form').addEventListener('submit', async event => { event.preventDefault(); try { const data = await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:event.currentTarget.elements.password.value})}); csrf=data.csrf; showDashboard(); } catch(error) { message(event.currentTarget,error.message); } });
$('#admin-list').addEventListener('click', event => { const button=event.target.closest('[data-id]'); if(button) edit(events.find(item=>item.id===button.dataset.id)); });
$('#new-event').addEventListener('click',()=>edit()); $('#cancel-edit').addEventListener('click',()=>editor.classList.add('hidden'));
editor.addEventListener('submit', async event => { event.preventDefault(); const saveButton=editor.querySelector('button[type="submit"]'); saveButton.disabled=true; try { const values=Object.fromEntries(new FormData(editor)); values.published=editor.elements.published.checked; values.externalOrganizer=editor.elements.externalOrganizer.checked; const id=values.id; delete values.id; const file=imageFile.files[0]; if(file) values.imageUpload={type:file.type,data:await imageAsBase64(file)}; message(editor,'Enregistrement de l’image et de l’événement…'); const saved=await api(id?`/api/events/${encodeURIComponent(id)}`:'/api/events',{method:id?'PUT':'POST',body:JSON.stringify(values)}); editor.elements.image.value=saved.image; imageFile.required=false; clearLocalImageUrl(); showImage(saved.image); imageFile.value=''; message(editor,'Image et événement enregistrés.',true); await loadEvents(); if(!id) editor.classList.add('hidden'); } catch(error) { message(editor,error.message); } finally { saveButton.disabled=false; } });
$('#delete-event').addEventListener('click', async()=>{ const id=editor.elements.id.value; if(!id || !confirm('Supprimer définitivement cet événement?')) return; try { await api(`/api/events/${encodeURIComponent(id)}`,{method:'DELETE'}); editor.classList.add('hidden'); await loadEvents(); } catch(error){ message(editor,error.message); } });
$('#logout').addEventListener('click',async()=>{ await api('/api/admin/logout',{method:'POST',body:'{}'}); location.reload(); });
api('/api/admin/session').then(data=>{csrf=data.csrf;showDashboard();}).catch(()=>{});

const contractEditor=$('#contract-editor');
const statusLabels={submitted:'À valider',approved:'Validé',sent:'Envoyé',client_signed:'Signature en cours',signed:'Signé',declined:'Refusé',cancelled:'Annulé'};
function contractStatusClass(status){return status==='signed'?'signed':status==='sent'||status==='client_signed'?'sent':'review';}
async function loadContracts(){contracts=await api('/api/contracts');const pending=contracts.filter(item=>item.status==='submitted').length;$('#contract-count').textContent=pending||'';$('#contract-count').classList.toggle('hidden',!pending);$('#contract-list').innerHTML=contracts.length?contracts.map(item=>`<button class="admin-contract" data-contract-id="${escapeHtml(item.id)}" type="button"><span><b>${escapeHtml(item.tenantName)}</b><small>${escapeHtml(new Intl.DateTimeFormat('fr-CA',{dateStyle:'long'}).format(new Date(`${item.eventDate}T12:00:00`)))} · ${escapeHtml(item.eventType)}</small></span><i class="status ${contractStatusClass(item.status)}">${escapeHtml(statusLabels[item.status]||item.status)}</i></button>`).join(''):'<p>Aucun contrat soumis.</p>';}
function editContract(contract){contractEditor.reset();contractEditor.classList.remove('hidden');for(const [key,value] of Object.entries(contract)){const field=contractEditor.elements[key];if(!field)continue;if(field.type==='checkbox')field.checked=Boolean(value);else field.value=value??'';}contractEditor.elements.accepted.value='true';$('#contract-status').textContent=statusLabels[contract.status]||contract.status;$('#contract-status').className=`status ${contractStatusClass(contract.status)}`;$('#contract-submitted').textContent=contract.submittedAt?`Soumis le ${new Intl.DateTimeFormat('fr-CA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(contract.submittedAt.replace(' ','T')+'Z'))}`:'';const locked=['sent','client_signed','signed'].includes(contract.status);[...contractEditor.elements].forEach(field=>{if(field.name&&!['id'].includes(field.name))field.disabled=locked;});$('#save-contract').classList.toggle('hidden',locked);$('#send-contract').classList.toggle('hidden',!['submitted','approved'].includes(contract.status));const download=$('#download-contract');download.classList.toggle('hidden',!contract.signedFileKey);download.href=`/api/contracts/${encodeURIComponent(contract.id)}/file`;message(contractEditor,'');contractEditor.scrollIntoView({behavior:'smooth',block:'start'});}
document.querySelectorAll('.admin-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.admin-tab').forEach(item=>item.classList.toggle('active',item===tab));document.querySelectorAll('.admin-panel').forEach(panel=>panel.classList.toggle('hidden',panel.id!==tab.dataset.panel));if(tab.dataset.panel==='contracts-panel')loadContracts();}));
$('#contract-list').addEventListener('click',event=>{const button=event.target.closest('[data-contract-id]');if(button)editContract(contracts.find(item=>item.id===button.dataset.contractId));});
$('#cancel-contract').addEventListener('click',()=>contractEditor.classList.add('hidden'));
contractEditor.addEventListener('submit',async event=>{event.preventDefault();const button=$('#save-contract');button.disabled=true;try{const values=Object.fromEntries(new FormData(contractEditor));values.minorsPresent=contractEditor.elements.minorsPresent.checked;values.accepted=true;const id=values.id;delete values.id;const saved=await api(`/api/contracts/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify(values)});message(contractEditor,'Contrat enregistré et prêt à être envoyé.',true);await loadContracts();editContract(saved);}catch(error){message(contractEditor,error.message);}finally{button.disabled=false;}});
$('#send-contract').addEventListener('click',async()=>{const button=$('#send-contract');button.disabled=true;try{const values=Object.fromEntries(new FormData(contractEditor));values.minorsPresent=contractEditor.elements.minorsPresent.checked;values.accepted=true;const id=values.id;delete values.id;await api(`/api/contracts/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify(values)});message(contractEditor,'Création de la demande de signature…');await api(`/api/contracts/${encodeURIComponent(id)}/send`,{method:'POST',body:'{}'});message(contractEditor,'Le contrat a été envoyé aux deux parties pour signature.',true);await loadContracts();editContract(contracts.find(item=>item.id===id));}catch(error){message(contractEditor,error.message);}finally{button.disabled=false;}});
