'use strict';
document.head.insertAdjacentHTML('beforeend', '<link rel="stylesheet" href="/events.css">');
let csrf = ''; let events = [];
const $ = selector => document.querySelector(selector);
const loginPanel = $('#login-panel'), dashboard = $('#dashboard'), editor = $('#event-form');
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]);
async function api(url, options = {}) { options.headers = { 'content-type':'application/json', ...(csrf ? {'x-csrf-token':csrf} : {}), ...options.headers }; const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Une erreur est survenue.'); return data; }
function message(form, text, ok = false) { const node = form.querySelector('.form-message'); node.textContent = text; node.classList.toggle('success', ok); }
function showDashboard() { loginPanel.classList.add('hidden'); dashboard.classList.remove('hidden'); $('#logout').classList.remove('hidden'); loadEvents(); }
async function loadEvents() { events = await api('/api/events'); $('#admin-list').innerHTML = events.length ? events.map(event => `<button class="admin-event" data-id="${escapeHtml(event.id)}" type="button"><span><b>${escapeHtml(event.title)}</b><small>${escapeHtml(new Intl.DateTimeFormat('fr-CA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(event.date)))}</small></span><i class="status ${event.published?'live':''}">${event.published?'Publié':'Brouillon'}</i></button>`).join('') : '<p>Aucun événement.</p>'; }
function edit(event = null) { editor.reset(); editor.classList.remove('hidden'); $('#editor-title').textContent = event ? 'Modifier l’événement' : 'Nouvel événement'; $('#delete-event').classList.toggle('hidden', !event); editor.elements.id.value = event?.id || ''; if (event) { for (const [key,value] of Object.entries(event)) if (editor.elements[key]) editor.elements[key].type === 'checkbox' ? editor.elements[key].checked = value : editor.elements[key].value = value; } else { editor.elements.location.value='99, rue Saint-Georges, Saint-Jérôme'; editor.elements.image.value='/assets/point-g-salle.jpg'; editor.elements.eventbriteId.value='1998914026663'; } editor.scrollIntoView({behavior:'smooth',block:'start'}); }
$('#login-form').addEventListener('submit', async event => { event.preventDefault(); try { const data = await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:event.currentTarget.elements.password.value})}); csrf=data.csrf; showDashboard(); } catch(error) { message(event.currentTarget,error.message); } });
$('#admin-list').addEventListener('click', event => { const button=event.target.closest('[data-id]'); if(button) edit(events.find(item=>item.id===button.dataset.id)); });
$('#new-event').addEventListener('click',()=>edit()); $('#cancel-edit').addEventListener('click',()=>editor.classList.add('hidden'));
editor.addEventListener('submit', async event => { event.preventDefault(); const values=Object.fromEntries(new FormData(editor)); values.published=editor.elements.published.checked; const id=values.id; delete values.id; try { await api(id?`/api/events/${encodeURIComponent(id)}`:'/api/events',{method:id?'PUT':'POST',body:JSON.stringify(values)}); message(editor,'Événement enregistré.',true); await loadEvents(); if(!id) editor.classList.add('hidden'); } catch(error) { message(editor,error.message); } });
$('#delete-event').addEventListener('click', async()=>{ const id=editor.elements.id.value; if(!id || !confirm('Supprimer définitivement cet événement?')) return; try { await api(`/api/events/${encodeURIComponent(id)}`,{method:'DELETE'}); editor.classList.add('hidden'); await loadEvents(); } catch(error){ message(editor,error.message); } });
$('#logout').addEventListener('click',async()=>{ await api('/api/admin/logout',{method:'POST',body:'{}'}); location.reload(); });
api('/api/admin/session').then(data=>{csrf=data.csrf;showDashboard();}).catch(()=>{});
