import { buildSignedContract } from '../../_contract_pdf.js';
import { clientIp, contractFromRow, contractSigningSnapshot, escapeHtml, json, logError, sendEmail, sha256 } from '../../_lib.js';

async function find(context){const hash=await sha256(String(context.params.token));return context.env.DB.prepare('SELECT * FROM contract_signers WHERE token_hash=?').bind(hash).first();}
export async function onRequestGet(context){try{const signer=await find(context);if(!signer||signer.expires_at<Date.now())return json({error:'Ce lien de signature est invalide ou expiré.'},404);const contract=contractFromRow(await context.env.DB.prepare('SELECT * FROM contracts WHERE id=?').bind(signer.contract_id).first());if(!contract)return json({error:'Contrat introuvable.'},404);return json({signer:{name:signer.name,email:signer.email,role:signer.role,status:signer.status,signedAt:signer.signed_at},contract});}catch(error){logError(error,context.request);return json({error:'Contrat indisponible.'},500);}}
export async function onRequestPost(context){
  try{const signer=await find(context);if(!signer||signer.expires_at<Date.now())return json({error:'Ce lien de signature est invalide ou expiré.'},404);if(signer.status==='signed')return json({error:'Vous avez déjà signé ce contrat.'},409);
    const input=await context.request.json();const name=String(input.name||'').trim().slice(0,180);const consent=input.consent===true;const signature=String(input.signature||'');if(!name||!consent)throw new Error('Confirmez votre nom et votre consentement.');if(!/^data:image\/png;base64,[A-Za-z0-9+/]+=*$/.test(signature)||signature.length>1500000)throw new Error('Veuillez dessiner votre signature.');
    const contract=contractFromRow(await context.env.DB.prepare('SELECT * FROM contracts WHERE id=?').bind(signer.contract_id).first());const documentHash=await sha256(JSON.stringify(contractSigningSnapshot(contract)));const bytes=Uint8Array.from(atob(signature.split(',')[1]),c=>c.charCodeAt(0));const signatureKey=`signatures/${signer.contract_id}/${signer.role}.png`;await context.env.CONTRACT_FILES.put(signatureKey,bytes,{httpMetadata:{contentType:'image/png'}});const consentText='Je confirme mon identité, avoir lu le contrat et vouloir le signer électroniquement.';
    await context.env.DB.batch([context.env.DB.prepare("UPDATE contract_signers SET status='signed',name=?,signature_method='drawn',signature_key=?,consent_text=?,signed_at=CURRENT_TIMESTAMP,signed_ip=?,user_agent=?,document_hash=? WHERE id=?").bind(name,signatureKey,consentText,clientIp(context.request),context.request.headers.get('user-agent')||'',documentHash,signer.id),context.env.DB.prepare("INSERT INTO contract_audit (contract_id,action,actor_role,actor_email,ip_address,user_agent,details) VALUES (?,'contract_signed',?,?,?,?,?)").bind(signer.contract_id,signer.role,signer.email,clientIp(context.request),context.request.headers.get('user-agent')||'',JSON.stringify({method:'drawn',documentHash,consentText}))]);
    const signed=await context.env.DB.prepare("SELECT * FROM contract_signers WHERE contract_id=? AND status='signed'").bind(signer.contract_id).all();
    if(signed.results.length===2){const pdfBytes=await buildSignedContract(context.env,context.request,contract,signed.results);const key=`signed/${signer.contract_id}.pdf`;await context.env.CONTRACT_FILES.put(key,pdfBytes,{httpMetadata:{contentType:'application/pdf'}});await context.env.DB.batch([context.env.DB.prepare("UPDATE contracts SET status='signed',signed_file_key=?,signed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(key,signer.contract_id),context.env.DB.prepare("INSERT INTO contract_audit (contract_id,action,details) VALUES (?,'contract_completed',?)").bind(signer.contract_id,JSON.stringify({documentHash,signers:signed.results.map(item=>({role:item.role,signedAt:item.signed_at}))}))]);let binary='';for(let offset=0;offset<pdfBytes.length;offset+=8192)binary+=String.fromCharCode(...pdfBytes.subarray(offset,offset+8192));const content=btoa(binary);for(const recipient of signed.results){await sendEmail(context.env,{to:recipient.email,subject:`Contrat signé — Salle Point G — ${contract.eventDate}`,html:`<p>Bonjour ${escapeHtml(recipient.name)},</p><p>Le contrat signé par les deux parties est joint à ce courriel.</p>`,attachments:[{filename:`contrat-salle-point-g-${contract.eventDate}.pdf`,content}]});}}
    else await context.env.DB.prepare("UPDATE contracts SET status='client_signed',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(signer.contract_id).run();
    return json({ok:true,complete:signed.results.length===2});
  }catch(error){logError(error,context.request);return json({error:error instanceof Error?error.message:'Signature impossible.'},400);}
}
